INSERT INTO activities (event_name, swipe) VALUES ('movie night', 0);
INSERT INTO activities (event_name, swipe) VALUES ('netflix and chill', 0);
INSERT INTO activities (event_name, swipe) VALUES ('gym date', 0);
INSERT INTO activities (event_name, swipe) VALUES ('bonfire', 0);
INSERT INTO activities (event_name, swipe) VALUES ('hike/park', 0);
INSERT INTO activities (event_name, swipe) VALUES ('concert', 0);
INSERT INTO activities (event_name, swipe) VALUES ('board game night', 0);
INSERT INTO activities (event_name, swipe) VALUES ('arcade/gaming night', 0);
INSERT INTO activities (event_name, swipe) VALUES ('shopping', 0);
INSERT INTO activities (event_name, swipe) VALUES ('bowling', 0);
INSERT INTO activities (event_name, swipe) VALUES ('taking a scenic drive', 0);
INSERT INTO activities (event_name, swipe) VALUES ('volunteer', 0);
INSERT INTO activities (event_name, swipe) VALUES ('take a painting class', 0);
INSERT INTO activities (event_name, swipe) VALUES ('take a cooking class', 0);
INSERT INTO activities (event_name, swipe) VALUES ('take a foreign language', 0);
INSERT INTO activities (event_name, swipe) VALUES ('take a pottery class', 0);
INSERT INTO activities (event_name, swipe) VALUES ('make dinner together', 0);
INSERT INTO activities (event_name, swipe) VALUES ('visit family/friends', 0);
INSERT INTO activities (event_name, swipe) VALUES ('attend a sporting event', 0);
INSERT INTO activities (event_name, swipe) VALUES ('ghost tour', 0);
INSERT INTO activities (event_name, swipe) VALUES ('mini golf', 0);
INSERT INTO activities (event_name, swipe) VALUES ('go to a dive bar', 0);
INSERT INTO activities (event_name, swipe) VALUES ('go to the symphony', 0);
INSERT INTO activities (event_name, swipe) VALUES ('tubing on a river', 0);
INSERT INTO activities (event_name, swipe) VALUES ('going to a neighborhood festival', 0);
INSERT INTO activities (event_name, swipe) VALUES ('getting a couples massage', 0);
INSERT INTO activities (event_name, swipe) VALUES ('watch a childhood favorite movie', 0);
INSERT INTO activities (event_name, swipe) VALUES ('build a fort', 0);
INSERT INTO activities (event_name, swipe) VALUES ('go to a local fair', 0);
INSERT INTO activities (event_name, swipe) VALUES ('go to an amusement park', 0);
INSERT INTO activities (event_name, swipe) VALUES ('plant a garden', 0);
INSERT INTO activities (event_name, swipe) VALUES ('binge watch a tv show', 0);
INSERT INTO activities (event_name, swipe) VALUES ('go dancing', 0);
INSERT INTO activities (event_name, swipe) VALUES ('play music together', 0);
INSERT INTO activities (event_name, swipe) VALUES ('have a cocktail night', 0);
INSERT INTO activities (event_name, swipe) VALUES ('dress up and go for a fancy night out', 0);
INSERT INTO activities (event_name, swipe) VALUES ('plan a vacation', 0);
INSERT INTO activities (event_name, swipe) VALUES ('go swimming', 0);
INSERT INTO activities (event_name, swipe) VALUES ('attend an art show', 0);
INSERT INTO activities (event_name, swipe) VALUES ('go to the bookstore/library', 0);
