INSERT INTO activities
    (event_name, event_img)
VALUES
    ('Movie Night','https://moneydotcomvip.files.wordpress.com/2014/11/141118_em_movieseats1.jpg'),
    ('Netflix and Chill','https://laurencecchi.com/wp-content/uploads/2017/01/netflix1-1000x700.jpg'),
    ('Gym Date','https://ballnroll.com/Uploads/Blogs/LoveDating/2014GymDate/Surviving%20The%20Gym%20Date.jpg'),
    ('Bonfire','https://i.pinimg.com/564x/1c/78/52/1c785215d823552f3a9fa30e9b95414e.jpg'),
    ('Hike/Park','https://i.pinimg.com/564x/3b/23/40/3b2340bb07de785d5fed49882cbc1030.jpg'),
    ('Concert','https://i.pinimg.com/564x/26/54/9d/26549d4b6ef4321e2dcac7affe61437e.jpg'),
    ('Board Game Night','https://www.studyfinds.org/wp-content/uploads/2019/02/AdobeStock_84428602-816x520.jpeg'),
    ('Arcade/Gaming Night','https://i.pinimg.com/564x/ae/85/4f/ae854fedb189edd925a5b4a5fdcd4917.jpg'),
    ('Shopping','https://media.gettyimages.com/videos/couple-shopping-in-slow-motion-video-id522166598?s=640x640'),
    ('Bowling','http://cdn.shopify.com/s/files/1/1141/1318/articles/bowling-date_1024x1024.jpg?v=1503370317'),
    ('Taking a Scenic Drive','http://newsmobile.in/wp-content/uploads/2014/02/roadtrip.gif'),
    ('Volunteer','https://www.gozaround.com/blog/wp-content/uploads/2016/02/Volunteer-Couple.jpg'),
    ('Take a Painting Class','https://img.grouponcdn.com/deal/c9vxUbVoAXNssC5CozUU/WR-2048x1229/v1/c700x420.jpg'),
    ('Take a Cooking Class','https://media.timeout.com/images/103939410/image.jpg'),
    ('Take a Foreign Language','https://www.state.gov/wp-content/uploads/2019/04/Language5_FSiStock2017.jpg'),
    ('Take a Pottery Class','https://www.whatcomtalk.com/wp-content/uploads/2015/05/jansen-art-center-pottery-date-night-600x600.jpg'),
    ('Make Dinner Together','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLLPudM6k2w8FCCWLKUGJOj18LRp1ncWIBDCJJEV52BPKuzUVn'),
    ('Visit Family/Friends','https://www.meetinggame.fr/reseau-de-loisirs/images/rencontres/couples-rencontres-amicales.jpg'),
    ('Attend a Sporting Event','https://d2cx26qpfwuhvu.cloudfront.net/aberdeen/wp-content/uploads/2018/05/02152937/ATLUTD.jpg'),
    ('Ghost Tour','http://www.historicpensacola.org/media/historic-pensacola/images/ghosttour08.jpg'),
    ('Mini Golf','https://datenightguide.com/wp-content/uploads/2018/05/Mini-golf-couple-shoot_023.jpg'),
    ('Go to a Dive Bar','http://www.trbimg.com/img-56048b4b/turbine/redeye-best-intentions-review-20150923'),
    ('Go to the Symphony','https://i.pinimg.com/originals/85/82/6c/85826cc7aed1a2527130768d0a7bc549.jpg'),
    ('Tubing on a River','http://cdn9.dissolve.com/p/D2027_1_722/D2027_1_722_0004_600.jpg'),
    ('Going to a Neighborhood Festival','https://spacecoast.files.wordpress.com/2015/04/maf-endless-crowd-2.jpg?w=1400&h=934'),
    ('Getting a Couples Massage','https://theravenspa.com/wp-content/uploads/2017/12/shutterstock_635175203.jpg'),
    ('Watch a Childhood Favorite Movie','https://data.whicdn.com/images/314823360/original.png?t=1531919306'),
    ('Build a Fort','https://i.pinimg.com/originals/bc/d9/fd/bcd9fd88e3af2e6c9672a330e0ce9319.jpg'),
    ('Go to a Local Fair','https://data.whicdn.com/images/235679294/superthumb.jpg?t=1461000398'),
    ('Go to an Amusement Park','https://s3.amazonaws.com/ttweddings/Williamsburg+Sessions/busch-gardens-williamsburg-sweetheart-session-09.jpg'),
    ('Plant a Garden','https://s3.envato.com/files/244495372/preview.jpg'),
    ('Binge Watch a TV Show','https://joshmitch.com/wp-content/uploads/2017/08/bingewatch.jpg'),
    ('Go Dancing','https://media.tenor.com/images/462611fa1c5be03400835de24d059c68/tenor.png'),
    ('Play Music Together','https://i.pinimg.com/originals/3c/4f/5c/3c4f5cdf510f6e0ef1a724b6345a8441.jpg'),
    ('Have a Cocktail Night','https://www.thematchmaker.ie/wp-content/uploads/2017/07/dating-couple.jpg'),
    ('Dress up and go for a Fancy Night Out','http://blog.kidzcentralstation.com/wp-content/uploads/Date-Night.jpg'),
    ('Plan a Vacation','https://images.pond5.com/young-couple-planning-vacation-trip-footage-074078931_prevstill.jpeg'),
    ('Go Swimming','https://s3.envato.com/files/201474541/preview.jpg'),
    ('Attend an Art Show','http://www.artsantafe.com/wp-content/uploads/2017/07/img_5306.jpg'),
    ('Go to the Bookstore/Library','https://i.pinimg.com/originals/b6/bd/f5/b6bdf5a138152dbef30b9a8e21e2eed8.jpg'),
    ('Go to the Zoo','https://media-cdn.tripadvisor.com/media/photo-s/0a/ef/ab/5c/couple-at-al-ain-zoo.jpg'),
    ('Go to the Aquarium','https://www.orlandodatenightguide.com/wp-content/uploads/2018/05/florida-aquarium-couple-2.jpg'),
    ('Scuba Diving', 'https://maltadiving.com/wp-content/uploads/2018/06/OW-4-600x400.jpg' );

INSERT INTO foods
    (meal_name, meal_img)
VALUES
    ('Hamburger','https://i.imgur.com/qFYDEhxb.jpg'),
    ('Turkey Burger','https://i.imgur.com/bx4wzSrb.jpg'),
    ('Chicken Sandwich','Chicken-Sandwich'),
    ('Chicken Strips','Chicken-Strips'),
    ('Hot Dog','Hot-Dog'),
    ('Taco','Taco'),
    ('Burrito','Burrito'),
    ('Beef Empanada','Beef-Empanada'),
    ('Chile Relleno','Chile-Relleno'),
    ('Chips and Salsa','Chips-and-Salsa'),
    ('Chicken Tikka Masala','Chicken-Tikka-Masala'),
    ('Samosas','Samosas'),
    ('Butter Chicken','Butter-Chicken'),
    ('Chickpea Curry','Chickpea-Curry'),
    ('Keema Aloo','Keema-Aloo'),
    ('Chicken Shawarma','Chicken-Shawarma'),
    ('Greek Chicken Souvlaki','Greek-Chicken-Souvlaki'),
    ('Greek Roasted Potatoes','Greek-Roasted-Potatoes'),
    ('Greek Salad','Greek-Salad'),
    ('Humus','Humus'),
    ('Jerk Chicken','Jerk-Chicken'),
    ('Ackee and Saltfish','Ackee-and-Saltfish'),
    ('Red Pea Soup','Red-Pea-Soup'),
    ('Brown Stew Chicken','Brown-Stew-Chicken'),
    ('Cornmeal Porridge','Cornmeal-Porridge'),
    ('Shrimp Etouffee','Shrimp-Etouffee'),
    ('Jambalaya','Jambalaya'),
    ('Gumbo','Gumbo'),
    ('Shrimp and Grits','Shrimp-and-Grits'),
    ('Blackened Catfish','Blackened-Catfish'),
    ('Tortellini Soup','Tortellini-Soup'),
    ('Baked Ziti with Sausage','Baked-Ziti-with-Sausage'),
    ('Gnocchi with Tomato Sauce and Mozzarella','Gnocchi-with-Tomato-Sauce-and-Mozzarella'),
    ('Baked Eggplant with Parmesan','Baked-Eggplant-with-Parmesan'),
    ('Beefy Baked Ravioli','Beefy-Baked-Ravioli'),
    ('Funnel Cake','Funnel-Cake'),
    ('Beignets','Beignets'),
    ('Taco Bell','Taco-Bell'),
    ('Homemade pizza','Homemade-pizza'),
    ('Hot wings','Hot-wings'),
    ('Lasagna','Lasagna'),
    ('One of your favorite childhood meals','One-of-your-favorite-childhood-meals');


INSERT INTO users
    (uniqueurl, acct_name, couple_name, secret_word, userone_name, usertwo_name)
VALUES
    (uuid(), 'test_couple', 'test couple', 'password', 'John', 'Jane'); 




